### ISSUE TITLE
About dot_map using

### ISSUE THREAD

**Issue by Yaozl2018** [gjy3035/NWPU-Crowd-Sample-Code#7]
I found that you use dot_map instead of density map as GT to supervise your model.
In **NWPUDataset()** of **baseddataset.py** :
`self.dotfileTemp = os.path.join(data_path, 'dot', '{}.png')`
`img, dot = self.read_image_and_gt(index)`
`return img, dot, attributes_pt`

However, you claim in your T-PAMI paper that your GT is density map instead of dot_map.
Could you tell me the reason for this difference?

**Comment by Yaozl2018** [comment]
Additonally, could you tell me the reason why you did the multiplication in **dot_transform** :
`own_transforms.tensormul(255.0)`

Actually, I found in your C3F codes that only Label normalization have been adopt:
`own_transforms.LabelNormalize(cfg_data.LOG_PARA)`
without
`own_transforms.tensormul(255.0)`.

In fact, 
`own_transforms.tensormul(255.0),
own_transforms.LabelNormalize(cfg_data.LOG_PARA),`
euqal to 
`own_transforms.LabelNormalize(cfg_data.LOG_PARA * 255)`.

When you out put the pred_count, you only divide **LOG_PARA**
`pred_cnt = np.sum(pred_map)/self.cfg_data.LOG_PARA`.

**Comment by gjy3035** [comment]
1. During the training, we use the density map instead of the dot map. The latter is only for saving the original head locations. In https://github.com/gjy3035/NWPU-Crowd-Sample-Code/blob/231620293687c82a4c1449195c3a4e7799fcd241/models/CC.py#L25, the dot map is transformed to the density map via a Gaussian conv kernel, which is an online operation for saving IO time compared with the original density file.

2. The density map is saved as a png file. When reading it using PIL, the pixel value is normalized [0,1] instead of [0, 255]. Thus, we need the ```tensormul``` operation.

**Comment by Yaozl2018** [comment]
> 
> 
>     1. During the training, we use the density map instead of the dot map. The latter is only for saving the original head locations. In https://github.com/gjy3035/NWPU-Crowd-Sample-Code/blob/231620293687c82a4c1449195c3a4e7799fcd241/models/CC.py#L25
>        , the dot map is transformed to the density map via a Gaussian conv kernel, which is an online operation for saving IO time compared with the original density file.
> 
>     2. The density map is saved as a png file. When reading it using PIL, the pixel value is normalized [0,1] instead of [0, 255]. Thus, we need the `tensormul` operation.

Thanks for your good job.
